### ISSUE TITLE
Breadcrumb with angle icon divider 

### ISSUE THREAD

**Issue by mojtabakaviani** [uikit/uikit#1038]
please add breadcrumb modifier class that can replace backslash divider with angle left/light icon for new design experience

**Comment by jerry1970** [comment]
It's a slash, not a backslash. But you can do it yourself. This from the UIKit css:
``` css
.uk-breadcrumb > li:nth-child(n+2)::before {
    content: "/";
    display: inline-block;
    margin: 0 8px;
}
```

You could override it in a CSS file of your own like this (25B6 is a black right-pointing triangle):
``` css
.uk-breadcrumb > li:nth-child(n+2)::before {
    content: "\25b6";
}
```

Or something from Fontawesome:
``` css
.uk-breadcrumb > li:nth-child(n+2)::before {
    content: "\f054"; /* chevron-right */
    font-family: Fontawesome;
}
```
