### ISSUE TITLE
Request: column-count responsive

### ISSUE THREAD

**Issue by rolandtoth** [uikit/uikit#1053]
CSS3 column-count is a great way to add columns. Unlike grid items or floats, elements are stacked vertically instead of horizontally.

It would be great to have something like this:
```css
.uk-column-large-4 {
  -moz-column-count: 4;
  -webkit-column-count: 4;
  column-count: 4;
}
.uk-column-medium-2 {
  -moz-column-count: 2;
  -webkit-column-count: 2;
  column-count: 2;
}
.uk-column-small-1 {
  -moz-column-count: 1;
  -webkit-column-count: 1;
  column-count: 1;
}
```
