### ISSUE TITLE
Stacked icons?

### ISSUE THREAD

**Issue by jerry1970** [uikit/uikit#1067]
Fontawesome has stacked icons. I needed that a few times in a project so I copied their code into what now looks like this and probably is far from perfect, but I now have the ability to stack text on an icon as well.

``` css
.uk-icon-stack {
    display: inline-block;
    height: 2em;
    line-height: 2em;
    position: relative;
    vertical-align: middle;
    width: 2em;
}
.uk-icon-stack i {
    left: 0;
    position: absolute;
    text-align: center;
    width: 100%;
    line-height: inherit !important;
}
.uk-icon-stack *:first-child {
    font-size: 2em;
}
/* when the second child is text and not an icon */
.uk-icon-stack span {
    display: inline-block;
    width: 2em;
    text-align: center;
    font-weight: bold;
}
```
