### ISSUE TITLE
Why "cursor: text" on "href=#"?

### ISSUE THREAD

**Issue by impressivewebs** [uikit/uikit#1180]
This is about [the line of code found here](https://github.com/uikit/uikit/blob/cef986253d603e6377b1ec28d607a904c3ee0b8b/src/less/core/navbar.less#L137), which is:

``` css
/* Appear not as link */
.uk-navbar-nav > li > a[href='#'] { cursor: text; }
```

I'm just curious why you would disable the default cursor on this element with this href attribute? It's common for demos and tutorials to use "#" as a value for href, so this seems to break the natural expectation here. For example, I'm publishing an article on SitePoint that uses [this demo](http://codepen.io/SitePoint/pen/doyXqB), so I had to override that line. I can't imagine a scenario where someone would want the cursor to appear as text in a navbar...?

Thanks!
