### ISSUE TITLE
Border radius in gradient theme gets overwritten

### ISSUE THREAD

**Issue by uikid** [uikit/uikit#1245]
The radius for the gradient theme gets overwritten with 0 px:

```css
.uk-form input, .uk-form select, .uk-form textarea {
    -moz-box-sizing: border-box;
    box-sizing: border-box;
    margin: 0;
    border-radius: 0;
    font: inherit;
    color: inherit
}
```

This layout example here would have border-radius 5px on the input fields and 0px for the submit-button, if you would use the version 2.20.3 with the gradient theme.

-> http://getuikit.com/docs/layouts_login.html

```html
    <form class="uk-panel uk-panel-box uk-form">
        <div class="uk-form-row">
            <input class="uk-width-1-1 uk-form-large" type="text" placeholder="Username">
        </div>
        <div class="uk-form-row">
            <input class="uk-width-1-1 uk-form-large" type="text" placeholder="Password">
        </div>
        <div class="uk-form-row">
            <a class="uk-width-1-1 uk-button uk-button-primary uk-button-large" href="#">Login</a>
        </div>
        <div class="uk-form-row uk-text-small">
            <label class="uk-float-left"><input type="checkbox"> Remember Me</label>
            <a class="uk-float-right uk-link uk-link-muted" href="#">Forgot Password?</a>
        </div>
    </form>
```
