### ISSUE TITLE
uk-grid issue in Safari

### ISSUE THREAD

**Issue by CinKon** [uikit/uikit#1294]
Safari has some issues with the flexbox:
https://jsfiddle.net/LqLt8d8t/2/

The Flexbox doesn't work 100% correctly in Safari (got another issue on another project, but can't remember currently...)

Anyway, the order of the Flexbox-Definition is important (and therefor slightly wrong in uikit): 
https://css-tricks.com/using-flexbox/

UIKit: 
```css
.uk-grid {
  display: -ms-flexbox;
  display: -webkit-flex;
  display: flex;
}
```

Correct:
```css
.uk-grid {
  display: -webkit-box;      /* OLD - iOS 6-, Safari 3.1-6 */
  display: -moz-box;         /* OLD - Firefox 19- (buggy but mostly works) */
  display: -ms-flexbox;      /* TWEENER - IE 10 */
  display: -webkit-flex;     /* NEW - Chrome */
  display: flex;             /* NEW, Spec - Opera 12.1, Firefox 20+ */
}
```
