### ISSUE TITLE
Zoom on hover

### ISSUE THREAD

**Issue by pimduijst** [uikit/uikit#1429]
Is it also possible to zoom in on an image on hover? And if so... how?

**Comment by malles** [comment]
Not the big zoom-functions you see in some webshops. The overlay component can provide a zoom effect: http://codepen.io/malles/pen/qEyEZr

**Comment by florianletsch** [comment]
Alternatively, you can use plain CSS for a similar effect.

```css
/* 1. optional: smoothes the scaling */
img {
  transition: transform ease 0.2s;
}

/* 2. here's the trick: zoom on hover */
img:hover {
  transform: scale(1.05);
}
```

Live example: http://codepen.io/florianletsch/pen/vNregz
