### ISSUE TITLE
Firefox still has issues with rendering css triangle: solved for tooltip

### ISSUE THREAD

**Issue by jerry1970** [uikit/uikit#1443]
Firefox (I've seen it on Windows and Unix) still has issues with rendering CSS triangles. For example, the tooltip has only half a triangle. (Yes, that is a triangle, too, but pointed in the wrong direction...

For the tooltip I've found an easy fix for this:

``` css
.uk-tooltip-top-left::after, .uk-tooltip-top-right::after, .uk-tooltip-top::after {
    border-color: #333 transparent transparent;
    border-style: solid;
    border-width: 5px;
    bottom: -10px;
    box-sizing: border-box;
    height: 5px;
    width: 5px;
}
```

Setting the box-sizing and the height and width did the trick. This is probably not the neatest solution, but it does the trick for me.

Could this be included?

Cheers,
Jerry
