### ISSUE TITLE
Bug micro clearfix combined with uk-list and floating image

### ISSUE THREAD

**Issue by xXiNiXx1** [uikit/uikit#1501]
When I align an image to the left of an `uk.list` the first `li` element will take the entire height of the image. This is caused by the micro clearfix. See code sample below

[Live code example - codepen](http://codepen.io/anon/pen/epmeyQ)

``` html
<div class="uk-clearfix">
  <img class="uk-align-left" src="https://placehold.it/100x100">
  <div>
    <ul class="uk-list">
      <li><a href="#">Item 1</a></li>
      <li class="uk-text-muted">Item 2</li>
      <li class="uk-text-muted">Item 3</li>
      <li class="uk-text-muted">Item 4</li>
      <li class="uk-text-muted">Item 5</li>
    </ul>
  </div>
</div>
```

``` css
/* POTENTIAL FIX ? */
.uk-list > li:before,
.uk-list > li:after {  
  display: inline-block; 
}
```
