### ISSUE TITLE
Feature Request:  Text wrapping without breaking up whole words

### ISSUE THREAD

**Issue by JerryCipriano** [uikit/uikit#1557]

**Comment by zslabs** [comment]
Do you just mean the [word-wrap](http://www.w3schools.com/cssref/css3_pr_word-wrap.asp) property?

**Comment by JerryCipriano** [comment]
I don't think so.  I am looking for behavior similar to .uk-text-break but that won't split a single word apart with a hyphen. 

For example, I'm looking for this:

>Prevent ugly
wrapping.

Not this:

>Prevent ugly wrap-
ping.

**Comment by zslabs** [comment]
`.uk-text-break` has the [hyphens](https://developer.mozilla.org/en-US/docs/Web/CSS/hyphens) property set to `auto`, which will cause those hyphens in the word-breaks. What I'd suggest is you just creating another utility class for your own purposes that only has what you need, for example:

    .uk-break-word { word-wrap: break-word; }

**Comment by JerryCipriano** [comment]
Thanks, this worked. 

```css
.uk-break-word 
{
		-moz-hyphens: none;
		-ms-hyphens: none;
		-webkit-hyphens: none;
		hyphens: none;
	}
```
