### ISSUE TITLE
uk-button-group breaks font-size and white-space for uk-dropdown-blank

### ISSUE THREAD

**Issue by campugnatus** [uikit/uikit#2057]
`.uk-button-group` has (among other things) the following styling:

``` css
.uk-button-group {
    font-size: 0;
    white-space: nowrap;
}
```

Which breaks things for the dropdowns  contained inside. Although `.uk-dropdown` restores `font-size` for itself, `.uk-dropdown-blank` doesn't do so, and neither of  the two restore white-space. The following seems to fix the problem for me:

``` css
.uk-dropdown-blank {
    font-size: 1rem;
    white-space: normal;
}
.uk-dropdown {
    white-space: normal;
}
```
