### ISSUE TITLE
Notify "info" and "primary" incorrect in docs or CSS?

### ISSUE THREAD

**Issue by nonadmin** [uikit/uikit#2138]
I noticed that the docs for the Notify component make reference to an "info" status.  This appears not to have any styling, and so the notice comes up with a black background from the base styling.  In CSS there is a "primary" class with the blue background you might expect.  

I was going to submit a PR to update the docs but I'm not sure if the primary class should be changed to info in the CSS or if the docs should be updated to reference "primary" instead of "info".

```css
/* Modifier: `uk-alert-info`
 ========================================================================== */
.uk-notify-message-primary {
  background: #ebf7fd;
  color: #2d7091;
  border-color: rgba(45, 112, 145, 0.3);
}
```

```javascript
UIkit.notify("...", {status:'info'}) // currently
UIkit.notify("...", {status:'primary'}) // should be?
```
