### ISSUE TITLE
UIkit3: How to use icons and dynamic font size ?

### ISSUE THREAD

**Issue by jack-theripper** [uikit/uikit#2228]
How to use icons and dynamic font size ?
I know about the `ration` options but it's just a static value.

sample code

```html
<div class="responsive-block">
     <span uk-icon="icon: cloud-upload"></span>
</div>
```
```css
@media (max-width: 123px) {
     .responsive-block {
          font-size: 150%; /* or 2.5em etc, just example */
     }
}
```

In the previous UIkit with FontAwesome you can easily control the size of icons and text size. I can not figure out how to do it is now? Anyone tell me. Thank you
