### ISSUE TITLE
I have to teach my clients to prefix everything including ul's?

### ISSUE THREAD

**Issue by uglyeoin** [uikit/uikit#2256]
Hi guys,

I have heard rave reviews about UI Kit, and I have to admit, it looks gorgeous.  But when I tried to use it I noticed I have to prefix everything.  

I can't just do 
`<ul> <li>`

I have to do
`<ul class="uk-list"><li>`

My clients will either forget to do this, or simply not bother.  Furthermore, I have to do it for every element, uk-button etc.

In Bootstrap ul's/buttons etc are already done, I just have to use Bootstrap and type `<button>` or `<ul>`.  Sure sometimes I have to add classes but not for everything.

I do see the value in having a prefixed framework, it stops clashes etc.  But couldn't you achieve the same result by adding `uk-body` to the body of the HTML and then using the CSS class `.uk-body ul`  `.uk-body button` this would save us a tonne of time and reduce the requirement to teach our end users.

Is there a reason you have decided not to work this way?

**Comment by florianletsch** [comment]
I think it depends on the use case. But if you want your clients to create content and not have them worry about adding classes, why not let them write in markdown (or HTML) and have the classes added automatically?

That is how we do it ourselves with the UIkit docs. The docs are written in Markdown, and all standard classes are added during rendering. We use the marked.js Markdown renderer for that, and have exchanged some of the default rendering functions: https://github.com/uikit/uikit-site/blob/develop/docs/app/util.js#L9

If you do not like it in JS, this can be done on the server side as well. In the Pagekit docs, for example, pretty much the same thing happens in PHP.

**Comment by BobbyBabes** [comment]
There is one more option (if you always want class `.uk-list` automatically applied to all `ul` elements).
You could try the `extend` feature of Less: http://lesscss.org/features/#extend-feature
I haven't done a regression test for lists though.

Less:
```less
ul:extend(.uk-list all) {}
```

should become CSS:
```css
.uk-list,
ul {
  padding: 0;
  list-style: none;
}
/*
 * Micro clearfix
 */
.uk-list > li::before,
.uk-list > li::after,
ul > li::before,
ul > li::after {
  content: "";
  display: table;
}

 /* Etc. */
```

Currently these CSS selectors would be extended with element `ul`. The first 2 are shown above.:

```CSS
/* ========================================================================
   Component: List
 ========================================================================== */
.uk-list {
  padding: 0;
  list-style: none;
}
/*
 * Micro clearfix
 */
.uk-list > li::before,
.uk-list > li::after {
  content: "";
  display: table;
}
.uk-list > li::after {
  clear: both;
}
/*
 * Remove margin from the last-child
 */
.uk-list > li > :last-child {
  margin-bottom: 0;
}
/*
 * Nested lists
 */
.uk-list ul {
  margin: 0;
  padding-left: 30px;
  list-style: none;
}
/*
 * Style
 */
.uk-list > li:nth-child(n+2),
.uk-list > li > ul {
  margin-top: 10px;
}
```
