### ISSUE TITLE
Are the "var-media-*" CSS classes safe to use?

### ISSUE THREAD

**Issue by BobbyBabes** [uikit/uikit#2280]
Looking at the following 4 CSS classes, and the comment above them, I checked the UIkit JS code. But these classes are not used.
So I wrote a tiny bit of JS to retrieve the 4 content values.
**But now I'm wondering, are these 4 classes not being used because they will be dropped in the near future?**

```CSS
/* Pass media breakpoints to JS
 ========================================================================== */
/*
 * Breakpoints
 */
.var-media-s:before {
  content: '640px';
}
.var-media-m:before {
  content: '960px';
}
.var-media-l:before {
  content: '1200px';
}
.var-media-xl:before {
  content: '1600px';
}
```
