### ISSUE TITLE
List inline pls

### ISSUE THREAD

**Issue by wozzup** [uikit/uikit#230]
add the List inline style
thanks

**Comment by unikum** [comment]
It's may be useful.

```css
.uk-list-inline > li {
  display: inline;
  list-style-type: none;
  padding-right: 20px;
  float: left;
}
```
