### ISSUE TITLE
Style broken on input["submit"] on mobile device

### ISSUE THREAD

**Issue by pbmarcano** [uikit/uikit#2558]
### UIkit version
3.0.0 beta-18

### Steps to reproduce

**Inspect on a live instance**
1. Inspect the [login form](https://turtledo.com/users/sign_in) on some app I am building.

**Try it yourself**
1. Make a form.
2. Assign the submit["input"] a class of "uk-button uk-button-primary"
3. Open on an iPhone? (I am currently downloading an android emulator to test on an android too)

### What is Expected?
Essentially `input.uk-button.uk-button-primary` styles fine on a web browser, and I would expect it to style the same way safari for iOS.

### What is actually happening?
On my iPhone's browser, the styling breaks on the "log in" button making a light blue oval with off centered text.

![img_2738](https://cloud.githubusercontent.com/assets/6471901/24413989/15dafc02-13ab-11e7-8362-845c264cf324.PNG)

if `class="uk-button uk-button-primary"` is set on an `a` or `button` element it works just as expected, just not on an `input["submit"]`.

### Other relevant information
The app is built in ruby on rails and has no other CSS besides a color modification to the navbar.

If I am doing something wrong, please correct my crap code!

Thanks!

**Comment by ninthspace** [comment]
It's a (long standing) Mobile Safari issue/convention which can be squashed by the following:

```css
textarea,
input.text,
input[type="text"],
input[type="button"],
input[type="submit"],
.input-checkbox {
  -webkit-appearance: none;
  border-radius: 0;
}
```

I think Bootstrap et. al. use something similar.
