### ISSUE TITLE
[IE] uk-align- overflows if container too small

### ISSUE THREAD

**Issue by Evanion** [uikit/uikit#262]
We just discovered that elements (ie < img />) contained inside a div with the classes uk-align or uk-float will cause the element to expand outside the parent of the uk-align element in modern IE (tested in IE11)

``` HTML
<div style="width:100px">
  <div class="uk-align-right">
    <img src="someimage.jpg" width=200 height=200 />
  </div>
</div>
```

This code will cause the image, and align elements to expand outside the first div.
The solution is to add the following CSS:

``` CSS
[class^='uk-align-'],
[class^='uk-float-'] {
  max-width:100%; }
```
