### ISSUE TITLE
Datepicker in v3

### ISSUE THREAD

**Issue by UteV** [uikit/uikit#2740]
Will a datepicker be included in v§ anytime soon or is there a way to transplant the code from v2 and get it running?

Thanks
Ute

### UIkit version

3.0.0-beta.25

**Comment by IRCraziestTaxi** [comment]
I love how this was a perfectly valid question with a real issue to address and it was closed without comments or anything.

**Comment by lucakuehne** [comment]
+1

**Comment by nvtin** [comment]
yes same for me. It's great if datepicker come with uikit 3 as it already on v2.

**Comment by KaKi87** [comment]
+1

**Comment by meatpaste** [comment]
+1 because https://www.caniuse.com/#search=date

**Comment by enrikas** [comment]
+1

**Comment by pepegarciag** [comment]
+1

**Comment by evolvens** [comment]
+1

**Comment by michielswaanen** [comment]
+1

**Comment by michielswaanen** [comment]
1 year later still no datepicker in v3. What's up with this feature?

**Comment by KaKi87** [comment]
Good question

**Comment by aarongerig** [comment]
@michielswaanen It‘s most likely not gonna happen. You should use a 3rd party library, something like flatpickr.

**Comment by michielswaanen** [comment]
@aarongerig That's unfortunately, this feature is something that every UI framework should have. Still hoping they will add it to v3 one day..

**Comment by KaKi87** [comment]
@aarongerig Why not ?

**Comment by aarongerig** [comment]
@KaKi87 Oh, that‘s just a guess and since UIkit is feature complete I simply don‘t think it‘s gonna happen.

**Comment by KaKi87** [comment]
Well, this issue is proof that it's not as complete as it seems ^^

**Comment by avedmigen** [comment]
Hello, friends!
Please add the following components to the Uikit framework:
1. Datepicker (example - https://buefy.org/documentation/datepicker/)
2. Numberinput (example - https://buefy.org/documentation/numberinput/)
3. Timepicker (example - https://buefy.org/documentation/timepicker/)

We need them! Thanks in advance!

**Comment by dsignr** [comment]
@avedmigen Wow, thank you for sharing, I've never heard of it before. But it looks way awesome than UIKIT. I'm tired of waiting for 2+ years for a simple datetime component ON A FRAMEWORK THAT ALREADY HAD IT: UiKit v2.0! Makes no sense..

**Comment by KaKi87** [comment]
Absolute nonsense right.

**Comment by dsignr** [comment]
I started worked on a project in 2017, that's finished now. We're working on v2 of the software now and were re-evaluating lot of frameworks since it's 2019 now. UIKIT was still a contender for its simplicity. Unfortunately lack of basic components like datepicker leads to code bloat because now I need to find and maintain some other third party library just for this single functionality. And I don't want to use Bootstrap which has its own set of issues (requiring jQuery is one). So I was on the lookout till I saw this issue and got to know Bulma. Looks simple, elegant and great. So will be switching from UIKIT to Bulma this week. I just gave it a spin and looks nice.

I don't mean to shit on the maintainers of this project, I mean thank you for your open source contributions and all, but this is a much requested feature for the last 2+ years and I think for a lot of people that's a deal breaker.

**Comment by dsignr** [comment]
I just came here to update that while Bulma is decent, it doesn't provide the convenience of UIKIT in many ways. The documentation is also far better on UIKIT than on Bulma. I found a way to port Bulma's datepicker into my project. UIKIT 3 wins on everything else, hands down.

**Comment by wtfdanny** [comment]
For anyone still looking for a good date/time picker that’s an easy drop in, check out [tail.DateTime](https://github.pytes.net/tail.DateTime/index.html). I’ve been using it with the Harx design and if fits in seamlessly (IMO) with UIkit.

**Comment by Valexr** [comment]
+1 & what about ColorPicker?

**Comment by timrasche** [comment]
@janschoenherr planned? or still a "wish"?

**Comment by tmt307** [comment]
UI Kit 3 is definitely missing a good few features from UI Kit 2 such as this date picker & HTML editor, I suspect a handful of other features are missing too, I do hope more features do come just it is a bit annoying for people who have already started using this new UI kit :(.

**Comment by michielswaanen** [comment]
Kinda sad that such a widely used library doesn't have more maintainers. This 'issue' has been going on for forever.

**Comment by KaKi87** [comment]
Hey, any news on this ? Thanks

**Comment by kildeby** [comment]
+1 !!

**Comment by 100ferhas** [comment]
+1

**Comment by tobiasbayer** [comment]
+1

**Comment by bommels** [comment]
+1

**Comment by ugalek** [comment]
+1

**Comment by chrisk8er** [comment]
no update? 😟

**Comment by fabrice-dresscodes** [comment]
+1

**Comment by yudin-clearscale** [comment]
+1

**Comment by vanling** [comment]
+1 bitte please

**Comment by MostafaAlsayedAhmed** [comment]
+1

**Comment by KaKi87** [comment]
62 thumbs up, 18 `+1`, 2 years, 11 months and 3 days later, still nothing.
WTF ?

**Comment by meatpaste** [comment]
> 62 thumbs up, 18 `+1`, 2 years, 11 months and 3 days later, still nothing.
> WTF ?

they have no obligation to lift a finger, this is open source software, you can either accept that, or submit a pull request with your own contribution

**Comment by KaKi87** [comment]
Well, I will only say it once because I already experienced how can that kind of conversation deviate a lot, but I feel like I must answer at least once.

> they have no obligation to lift a finger, this is open source software, you can either accept that, or submit a pull request with your own contribution

Despite all open source developers always hide themselves behind the "software provided without any warranty" thing, I still think that creating a project, even open source, implies a minimum moral responsibility to the users.

I feel that when multiple people ask me for the same feature, I _must_ provide it.
I feel that if I woudn't, I would be a _jerk_ to them.
I feel that it would be like saying out loud : "I know my software by heart, so I know it wouldn't take me much to help you guys, but I really prefer letting you down".

Or, if you prefer, it's like letting a child be born and then abandon it.

**Comment by yaeru** [comment]
+1

**Comment by andy-scboy** [comment]
+1

**Comment by alexmarginean16** [comment]
+1

**Comment by paulracoon** [comment]
+1

**Comment by iambumblehead** [comment]
One solution is to use pikaday: here's [the demo page][0] and here's [the github project page.][1] If pikaday looks good enough for you, try adding it to your app.

<details>
  <summary>get pikaday into your project npm or html</summary>

```html
<script src="https://cdn.jsdelivr.net/npm/pikaday/pikaday.js"></script>
<link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/pikaday/css/pikaday.css">
```

</details>

<details>
  <summary>add dark-mode and ui-kit reset styles</summary>

below are modified versions of [another variant found here.][2]

```css
.pikaday-dark {
    --backgroundColor: #2d3748;
    --textColor: #f7fafc;
    --currentDateTextColor: #3182ce;
    --selectedDateBackgroundColor: #3182ce;
    --selectedDateTextColor: #f7fafc;

    --labelTextColor: #3182ce; /* eg. May 2020 */
    --weekDaysTextColor: #a0aec0; /* eg. Mo Tu We ....*/

    background-color: var(--backgroundColor);
    border-radius: 10px;
    border: 0;
    padding: 0.7rem;
    z-index: 2000;
    margin: 6px 0 0 0;
    box-shadow: 0 1px 2px 0 rgba(60, 64, 67, .30), 0 1px 3px 1px rgba(60, 64, 67, .15);
    font-family: inherit;
}
.pikaday-dark .pika-prev {
    background-image: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' fill='none' viewBox='0 0 24 24' stroke='%23a0aec0'%3E%3Cpath stroke-linecap='round' stroke-linejoin='round' stroke-width='2' d='M15 19l-7-7 7-7'%3E%3C/path%3E%3C/svg%3E");
}
.pikaday-dark .pika-next {
    background-image: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' fill='none' viewBox='0 0 24 24' stroke='%23a0aec0'%3E%3Cpath stroke-linecap='round' stroke-linejoin='round' stroke-width='2' d='M9 5l7 7-7 7'%3E%3C/path%3E%3C/svg%3E");
}
.pika-prev.is-disabled,
.pika-next.is-disabled {
    cursor: default;
    opacity: 0.05;
}
.pikaday-dark .pika-label {
    color: var(--labelTextColor);
}
.pikaday-dark table th {
    color: var(--weekDaysTextColor);
}

/* remove underline from mon tue wed ... */
.pikaday-dark table th abbr {
    text-decoration: none;
    pointer-events:none;
}
.pikaday-dark table td button:hover {
    background-color: var(--selectedDateBackgroundColor);
}
.pikaday-dark table td.is-today button {
    color: var(--currentDateTextColor);
}
.pikaday-dark table td.is-selected button {
    background-color: var(--selectedDateBackgroundColor);
}
.pikaday-dark .pika-label {
    background-color: var(--backgroundColor);
}
.pikaday-dark table td button,
.pikaday-dark table td button:hover {
    color: var(--textColor);
    background-color: var(--backgroundColor);
}
.pikaday-dark table td.is-selected button,
.pikaday-dark table td.is-selected button:hover {
    color: var(--textColor);
    background-color: var(--selectedDateBackgroundColor);
}
```

</details>


<details>
  <summary>add scripting to show pikaday</summary>

``` javascript
window.picker = new Pikaday({
  field: vnode.elm,
  minDate: new Date(data.min),
  maxDate: new Date(data.max),
  theme: 'pikaday-dark',
  position: 'top left',
  defaultDate: new Date(data.max),
  yearRange: [
    new Date(data.min).getFullYear(),
    new Date(data.max).getFullYear()
  ],
  onSelect: function () {
    console.log('selected');
  }
})
```

</details>


In my particular case, the default date-picker input for non-firefox browsers was usable, so my app conditionally renders pikaday for firefox, otherwise a native text input using .uk-input styles.

<details>
  <summary>conditionally render pikaday or native input (snabbdom)</summary>
  
``` javascript
const renderInputDateNative = (data, name, labelprimary) => (
  div('.uk-margin.uk-text-left', [
    label('.uk-span', { props: { for: name } }, capitalize(labelprimary)),
    div('.uk-inline.uk-width-1-1.uk-relative', [
      input('.uk-input.uk-form-large.uk-border-rounded', {
        id: name,
        props: {
          type: 'date',
          min: data.min, // yyyy-dd-mm, '2018-01-01'
          max: data.max, // yyyy-dd-mm, '2018-01-01'
          name,
          value: data.values[name]
        },
        on: {
          click: ev => ev.srcElement.showPicker(),
          focus: ev => ev.srcElement.showPicker()
        }
      })
    ])
  ])
);

const renderInputDateScripted = (data, name, labelprimary, placeholder) => (
  div('.uk-margin.uk-text-left', [
    label('.uk-span', { props: { for: name } }, capitalize(labelprimary)),
    div('.uk-inline.uk-width-1-1.uk-relative', [
      input('.uk-input.uk-form-large.uk-border-rounded', {
        id: name,
        hook: {
          insert: vnode => {
            window.picker = new Pikaday({
              field: vnode.elm,
              minDate: new Date(data.min),
              maxDate: new Date(data.max),
              theme: 'pikaday-dark',
              position: 'top left',
              defaultDate: new Date(data.max),
              yearRange: [
                new Date(data.min).getFullYear(),
                new Date(data.max).getFullYear()
              ],
              onSelect: function () {
                // console.log(this.getMoment().format('Do MMMM YYYY'));
              }
            });
          }
        },
        props: {
          placeholder,
          type: 'text',
          name,
          value: data.values[name]
        }
      })
    ])
  ])
);

const renderInputDate = /firefox/i.test(navigator.userAgent)
  ? renderInputDateScripted
  : renderInputDateNative;
```

</details>



[0]: https://pikaday.com/
[1]: https://github.com/Pikaday/Pikaday
[2]: https://gist.github.com/mithicher/2266302fd2040b9acdd055b24baf224d
