### ISSUE TITLE
Issue with form icons padding when combined with size modifiers

### ISSUE THREAD

**Issue by miljan-aleksic** [uikit/uikit#2744]
### UIkit version
3.0.0-beta.25

### Steps to reproduce

Set `uk-form-small` to an input with form icon.

```
<div class="uk-inline">
    <span class="uk-form-icon" uk-icon="icon: user"></span>
    <input class="uk-input uk-form-small">
</div>
```

### What is Expected?

The same behavior as without the `uk-form-small` class.

### What is actually happening?

The left padding is removed by the class.

**Comment by oshihirii** [comment]
[Codepen of comparative small, default and large inputs with icons](https://codepen.io/oshihirii/pen/wqNOVP)

It seems this:
```css
.uk-form-large:not(textarea):not([multiple]):not([size]) {
    height: 55px;
    padding-left: 12px;
    padding-right: 12px;
}
```
and this:
```css
.uk-form-small:not(textarea):not([multiple]):not([size]) {
    height: 30px;
    padding-left: 8px;
    padding-right: 8px;
}
```
is overriding this:
```css
.uk-form-icon:not(.uk-form-icon-flip) + .uk-input {
    padding-left: 40px
}
```
If you change to this, it looks uniform:
```css
.uk-form-icon:not(.uk-form-icon-flip) + .uk-input {
    padding-left: 40px !important;
}
