### ISSUE TITLE
[Feature Request] uk-height-1-1@breakpoint

### ISSUE THREAD

**Issue by OwenMelbz** [uikit/uikit#2780]
Hi Guys,

Today we chugging along as usual, end ended up coming against a few instances where I needed

```css
.uk-height-1-1\@m {
    @media(min-width: $medium-min) {
        height: 100%;
    }
}
```

Wondering if it would be an idea to include this in the core with any other breakpoints? I can put in a PR if you guys wanted?
