### ISSUE TITLE
Input file cursor not showing the pointer

### ISSUE THREAD

**Issue by lowsprofile** [uikit/uikit#3137]
Input file cursor not showing the pointer, but when I look at the style it's default already pointer, why?
```css
.uk-form-custom input[type=file], .uk-form-custom select {
    position: absolute;
    top: 0;
    z-index: 1;
    width: 100%;
    height: 100%;
    left: 0;
    -webkit-appearance: none;
    opacity: 0;
    cursor: pointer;
}
```
