### ISSUE TITLE
How to change accordion icon color?

### ISSUE THREAD

**Issue by dalenguyen** [uikit/uikit#3204]
Hi everyone, 

Are there any ways that we can change the color of the icon on the accordion by using CSS? 

![image](https://user-images.githubusercontent.com/14116156/35815699-212324be-0a67-11e8-8d7d-88523135b76e.png)

Thanks,

**Comment by aarongerig** [comment]
@dalenguyen Yes there is a way:

```css
/* Default state */
.uk-accordion-title::after {
    background-image: url('your-image');
}

/* Open state */
.uk-open>.uk-accordion-title::after {
    background-image: url('your-image');
}
```
