### ISSUE TITLE
** Feature Request ** Image component add class to image when loaded to show it with smooth transitions.

### ISSUE THREAD

**Issue by zzseba78** [uikit/uikit#3387]
New Image component it´s a great addition, it would be great to be able to specify a class ( or uikit automatically add it ) to the image when it´s loaded, so it´s possible to add some cool and smooth transitions on image while they load.

Thanks for your work. UIkit 3 it´s really amazing.

**Comment by zzseba78** [comment]
I try it with some css attributes selectors, works fine in Firefox and Chrome, but not on Safari ( both pc and mobile ) and in Chrome mobile.

Maybe adding a class could be more "clean" solution, i will leave this open if you want to consider it, thanks! UIkit rocks :metal:

**Comment by saschadube** [comment]
You test is not working for me. Using the selectors for the animation should work in all browsers. Here are 3 selectors for all 3 states:

```css
/* Initial state: Image hidden (because to hide alt text) */
img:not([src]) { visibility: hidden; }

/* Placeholder state: Image is not loaded, yet */
img[src^='data:image'] { ... }

/* End state: Image shown (Placeholder is replaced) */
img[src]:not[src^='data:image'] { ... }
```

Don't worry about the HTML validation. It's absolutely fine. The HTML is valid as soon as the JavaScript is executed. No issue here.
