### ISSUE TITLE
Adding background color to body doesn't work

### ISSUE THREAD

**Issue by akshaybabloo** [uikit/uikit#3555]
Trying to change the body background colour by overriding `uk-background-default` adding it to `body` does nothing.

![capture](https://user-images.githubusercontent.com/7360286/44895342-08b30280-ad48-11e8-85a7-ef0233d66912.PNG)

### UIkit version

3.0.0-rc.12

### Browser

Chrome 68

### Steps to reproduce

Override `uk-background-default` by adding 

```css
.uk-background-default{
    background-color: #1d1f21 !important;
}
```

and add it to 

```html
<body class="uk-background-default">
...
</body>
```

### What is Expected?

The background colour of the body should change.

### What is actually happening?

Nothing happens

**Comment by Camel-Black** [comment]
why this issue closed?ive same problem

**Comment by akshaybabloo** [comment]
No reply since 2 years. Closing it

**Comment by soheshts** [comment]
How can I give background color to body?

**Comment by akshaybabloo** [comment]
this should help @soheshts 

```css
body {
  background-color: #fff !important;
}
```
