### ISSUE TITLE
.uk-open:before inheritance error

### ISSUE THREAD

**Issue by Evanion** [uikit/uikit#36]
This was originally reported on the YOOtheme forum.

The border that creates the top arrow in the menu dropdown is set to inherit from @theme_global-dark-background (navbar.less):

``` less
.uk-navbar-nav .uk-open:before {  
    content: '';  
    position: absolute;  
    left: 50%;  
    bottom: -@dropdown-navbar-margin;  
    margin-left: -@theme_navbar-nav-open-arrow-width + (@theme_navbar-nav-margin-left/2);  
    border-right: @theme_navbar-nav-open-arrow-width solid transparent;  
    border-bottom: @theme_navbar-nav-open-arrow-height solid @theme_global-dark-background; // <-- this row  
    border-left: @theme_navbar-nav-open-arrow-width solid transparent;  
    -webkit-animation: @dropdown-animation 0.2s ease-in-out;  
    animation: @dropdown-animation 0.2s ease-in-out;  
    z-index: 10;  
}
```

This causes the arrow to become the wrong color if you change the background of the dropdown in the customizer, instead the variable should be changed to use '@dropdown-navbar-background' that defines the background for the dropdown.
