### ISSUE TITLE
$leader-fill-content 

### ISSUE THREAD

**Issue by suntrop** [uikit/uikit#3675]
### UIkit version
3.0.0-rc.24

### Browser
Safari, Chrome
### Reproduction Link
https://codepen.io/suntrop/pen/WYaGEw
(Note: I replaced the link to Uikit CDN CSS file with my compiled)

I have a problem with the Leader component. Instead of the dots I see printed "$leader-fill-content" multiple times. I have no idea why. When using the default/CDN CSS file it works, but not when I compile it on my own (CodeKit).

Any idea what is wrong or how to fix? Is something wrong with my compiler? I tried to remove all my code, but it is still not working correctly.

**Comment by stephanvane** [comment]
Which compiler did you use? I ran into the same problem. I know that the `ruby-sass` compiler (version 3.7.2) causes a problem with the following scss (extracted from `leader.scss`):

```scss
$leader-fill-content: unquote('.') !default;
  
.uk-leader-fill-content::before { content: '#{$leader-fill-content}'; }
:root { --uk-leader-fill-content: $leader-fill-content; }
```

This is being compiled to:

```scss
.uk-leader-fill-content::before {
  content: "."; }

:root {
  --uk-leader-fill-content: $leader-fill-content; }
```

instead of:

```scss
.uk-leader-fill-content::before {
  content: "."; }

:root {
  --uk-leader-fill-content: .; }
```
