### ISSUE TITLE
Tooltip on disabled elements

### ISSUE THREAD

**Issue by miljan-aleksic** [uikit/uikit#422]
Hi,

by default Tooltip will skip disabled elements. If this is intentional I would like to suggest making it possible.

For example a button which has a tooltip on it, explaining what does it do, if disabled it could be explaining the reasons behind it's status.

**Comment by Semmu** [comment]
Still missing this feature. Wrapper element workaround doesn't work if there is only a disabled button as a child.

**Comment by razvanioan** [comment]
```css
.uk-disabled, [disabled] {
  pointer-events: all;
  cursor: default;
}

.uk-disabled *, [disabled] * {
  cursor: default;
}
```
