### ISSUE TITLE
Tooltip visibility

### ISSUE THREAD

**Issue by lbreza** [uikit/uikit#4268]
### Summary

Add new attributes **visible** and **hide** to the uk-tooltip.

For example if you want to show tooltip for medium and larger screens:
`uk-tooltip="title: Hello World; pos: top-left; visible: m"`

For example if you want to hide tooltip for larg and larger screens:
`uk-tooltip="title: Hello World; pos: top-left; hide: l"`

### Priority

Pretty useful feature. Especially for responsive content. In my case at web chat I'm showing usernames only at medium or larger screens. At small screen i display username with tooltip (hover on user image).

Would love to see that feature in UIKit.

**Comment by bornova** [comment]
Hi @lbreza , that would be cool feature. In the meantime (ignore if you are already doing this) here is a css only solution for what you are trying to accomplish:

```css
.uk-tooltip {
    display: none !important;
}

@media (max-width: 639px) {
    .uk-tooltip {
        display: block !important;
    }
}
```

**Comment by lbreza** [comment]
> Hi @lbreza , that would be cool feature. In the meantime (ignore if you are already doing this) here is a css only solution for what you are trying to accomplish:
> 
> ```css
> .uk-tooltip {
>     display: none !important;
> }
> 
> @media (max-width: 639px) {
>     .uk-tooltip {
>         display: block !important;
>     }
> }
> ```

Hello @bornova.

Thank you for your suggestion. This would actually work if I would like to hide all the tooltips but the problem is that I want to hide only the specific ones. For example I use tooltips at side navigation and in my chat user selection which i want to hide for medium and larger screens.

**Comment by bornova** [comment]
In that case, you can pass a custom class to the tooltips for which you want this behaviour: `uk-tooltip="cls: uk-active custom"`

Then apply the css I suggested to the custom class:

```css
.custom {
    display: none !important;
}

@media (max-width: 639px) {
    .custom {
        display: block !important;
    }
}
```

Working example: [https://jsfiddle.net/prgahu3o/](https://jsfiddle.net/prgahu3o/)
