### ISSUE TITLE
Off-canvas dynamically size 

### ISSUE THREAD

**Issue by mits87** [uikit/uikit#4302]
Hi there, 

I would like to change size of off-canvas (with size) and actually I checked in documentation and there is no option to do that. 
Do you have any idea how can I do that ?

The best solution could be dynamically set size like: 
```
uikit.offcanvas(drawerRef.value.$el, { width: 200 }).show();
```

or 
```
uk-offcanvas="overlay: true; bg-close: false; flip: true; width: 200"
```

What do you think?

**Comment by zzseba78** [comment]
Offcanvas have a mobile and desktop size that you can edit: Less example: https://github.com/uikit/uikit/blob/5ba2be165ccfb58b1ca44c98846e409bf5c41d1e/src/less/components/offcanvas.less#L28-L34

**Comment by mits87** [comment]
hmm gotcha, so how can decide about the offcanvas size (for mobile, desktop etc.) for every of my page? 
For example in `page1` the size should be 270px and ing `page2` 350px? 

Some advice?

**Comment by zzseba78** [comment]
@mits87 You can create a modifier css class to apply.
https://codepen.io/zzseba78/pen/BazrwOr

**Comment by mits87** [comment]
I tried by myself like that but if you set for example: 
```.uk-offcanvas-bar.offcanvas-small {
  width:800px;
}```

then the animation for hide off-canvas works bad. 
That's why I created this feature request.

**Comment by BernhardBaumrock** [comment]
I agree that this would be very helpful!

This is what I came up with in several projects making every offcanvas having the `.tm-offcanvas` class on the `.uk-offcanvas-bar` element fixed width of `XXX` pixels and max-width of `100vw`.

Here is a working fiddle: https://jsfiddle.net/baumrock/32atcshg/2/

@janschoenherr what do you think?

```less
// offcanvas customization
@tm-offcanvas-width: 800px;

/* bar width */
.uk-offcanvas-bar.tm-offcanvas {
  left: -@tm-offcanvas-width;
  width: @tm-offcanvas-width;
  max-width: 100vw;
}
@media (min-width: @breakpoint-medium) {
  .uk-offcanvas-bar.tm-offcanvas {
      left: -@tm-offcanvas-width;
      width: @tm-offcanvas-width;
  }
}
.uk-offcanvas-flip .uk-offcanvas-bar.tm-offcanvas {
  left: auto;
  right: -@tm-offcanvas-width;
}
@media (min-width: @breakpoint-medium) {
  .uk-offcanvas-flip .uk-offcanvas-bar.tm-offcanvas { right: -@tm-offcanvas-width; }
}

/* Open */
.uk-open > .uk-offcanvas-bar.tm-offcanvas { left: 0; }
.uk-offcanvas-flip .uk-open > .uk-offcanvas-bar.tm-offcanvas {
  left: auto;
  right: 0;
}

/* reveal */
.uk-offcanvas-reveal .uk-offcanvas-bar.tm-offcanvas {
  left: 0;
}
.uk-offcanvas-flip .uk-offcanvas-reveal .uk-offcanvas-bar.tm-offcanvas {
  left: auto;
  right: 0;
}
.uk-open > .uk-offcanvas-reveal { width: @tm-offcanvas-width; }
@media (min-width: @breakpoint-medium) {
  .uk-open > .uk-offcanvas-reveal { width: @tm-offcanvas-width; }
}
.uk-offcanvas-flip .uk-offcanvas-reveal {
  right: 0;
  left: auto;
}

/*
* Activate slide-out animation
*/
:not(.uk-offcanvas-flip).uk-offcanvas-container-animation { left: @tm-offcanvas-width; }
.uk-offcanvas-flip.uk-offcanvas-container-animation { left: -@tm-offcanvas-width; }
@media (min-width: @breakpoint-medium) {
  :not(.uk-offcanvas-flip).uk-offcanvas-container-animation { left: @tm-offcanvas-width; }
  .uk-offcanvas-flip.uk-offcanvas-container-animation { left: -@tm-offcanvas-width; }
}
```
