### ISSUE TITLE
Fix when offcanvas-bar-width is greater than viewport width

### ISSUE THREAD

**Issue by BernhardBaumrock** [uikit/uikit#4408]
### UIkit Version

*Check if the issue is reproducible with the latest stable version.*
3.6.5

BTW: You could add a note where to find the uikit version to save others from searching (like I had to do) ;) `/dist/css/uikit.css`

### Actual Behavior

I'm using wider offcanvas for my app and that causes a problem on mobile devices:

![image](https://user-images.githubusercontent.com/8488586/107201543-6956c700-69f9-11eb-828e-df595eb32139.png)

Fix:
```less
@offcanvas-bar-width: 600px;
@media(max-width: @offcanvas-bar-width) {
  .uk-offcanvas-bar { max-width: 100vw; }
}
```

![image](https://user-images.githubusercontent.com/8488586/107201609-7d9ac400-69f9-11eb-9d47-0fb5616c2851.png)

### Expected Behavior

The offcanvas should never be wider than the viewport.
