### ISSUE TITLE
tooltip breaks when using file paths

### ISSUE THREAD

**Issue by BernhardBaumrock** [uikit/uikit#4585]
### UIkit Version

3.11.1

https://jsfiddle.net/baumrock/4q9wrd38/13/

**Comment by bornova** [comment]
I am having the same issue.  As a workaround, you can try adding the following to your css:
```css
.uk-tooltip-inner {
  overflow-wrap: break-word;
}
```
