### ISSUE TITLE
uk-visible @ wrong window size

### ISSUE THREAD

**Issue by 0FaKE** [uikit/uikit#4594]
### UIkit Version

3.13.1

### Actual Behavior

The classes `uk-visible@s`, `uk-visible@m`, `uk-visible@l`, `uk-visible@xl` **don't** respect the right windows size.

According to the docs elements with those classes should begin to be visible at:

![grafik](https://user-images.githubusercontent.com/19412863/159137486-7db8908a-df05-47e7-8764-03e4fe6734e7.png)

Those elements are already visible if the current window size is **1 pixel less**.
(`@s` visible at 639px, `@m` visible at 959px, `@l` visible at 1199px, `@` visible at 1599px)

For example:
```css
@media (max-width: 959px) {
   .uk-visible\@m {
      display: none !important;
   }
}
```

The media query condition `max-width: 959px` actually **does not** include 959px but 958px.

![image](https://user-images.githubusercontent.com/19412863/159138096-ecdd27b8-3097-423b-834c-5817f39617b1.png)

### Steps to Reproduce the Problem

1. Open any browser (tested on Safari, Firefox, Edge, Chrome)
2. Use the inspection tool
3. Scale the window size to 959px
4. Elements with the class `uk-visible@m` will already show up and not if the window size >= 640px

**Comment by 0FaKE** [comment]
I can actually reproduce the issue in any browser I'm tested (most mentioned above).
The issue also exists on when I test stuff at `codepen.io`.
For some reason `jsfiddle.net` doesn't have that issue.

After doing some tests I found a solution which yet works in any browser I tested.
By assigning floats to the `max-width` condition, the issue seems to be gone.

```css
@media (max-width: 639.9px)
{
	.uk-visible\@s
	{
		display: none !important;
	}
}

@media (max-width: 959.9px)
{
	.uk-visible\@m
	{
		display: none !important;
	}
}

@media (max-width: 1199.9px)
{
	.uk-visible\@l
	{
		display: none !important;
	}
}

@media (max-width: 1599.9px)
{
	.uk-visible\@xl
	{
		display: none !important;
	}
}
```
