### ISSUE TITLE
Navbar item padding removed in 3.15.0 causing display issue

### ISSUE THREAD

**Issue by chriswthomson** [uikit/uikit#4638]
The padding on navbar items has been removed in 3.15.0 leading to the first and last items in the navbar being hard against the edge of the container.

This can currently be seen in the examples at https://getuikit.com/docs/navbar.

Perhaps uk-navbar-container should have L/R padding, maybe if the element is given an additional uk-container class?

```html
<nav class="uk-navbar-container uk-container" uk-navbar></nav>
```

```css
.uk-navbar-container.uk-container {
    padding: 0 15px;
}
```
