### ISSUE TITLE
Please add a setting to lightbox to always show the UI

### ISSUE THREAD

**Issue by BernhardBaumrock** [uikit/uikit#4874]
### Summary

I'm using uk-lightbox and it's great. I'm showing a booking service on a website for a doctor. The problem is that when not moving the mouse on that page for some time the UI completely disappears and it might not be obvious to visitors that they can close the lightbox after they have booked an appointment.

I have this fix in place, but that makes the UI stay visible across all lightboxes on the site. On galleries it might be nice to hide the UI after some time, so it would be great to have a setting for that.

```css
.uk-lightbox .uk-transition-slide-top {
    transform: translateY(0) !important;
}
.uk-lightbox .uk-transition-slide-bottom {
    transform: translateY(0) !important;
}
```

Maybe something like this?

```html
<div uk-lightbox="hideui: false;">...</div>
```

Where `hideui` could define the delay in ms or stay visible all the time if using `false`?

### Priority

4 - I've had that need several times, for example when showing youtube videos in iframes where the close button disappears as well.

Thx in advance!
