### ISSUE TITLE
why the misterious -35 px for the left margin

### ISSUE THREAD

**Issue by cocodrino** [uikit/uikit#648]
Sorry I'm backend and I don't know many tricks used by frontends but I found pretty weird this

``` css
 .uk-grid:not(.uk-grid-preserve) { margin-left: -35px;}
```

and actually it  has caused me frecuently headaches and need restore to 0 px....Am I doing something wrong??...
