### ISSUE TITLE
Form input type=submit incorrect styling (Uikit v2.11)

### ISSUE THREAD

**Issue by john052** [uikit/uikit#671]
The button styling for an input element with type="submit" on a uk-form is displaying incorrectly. The border radius is removed and the font color is incorrect.

Specifically, the following CSS seems to be causing the problem

``` css
.uk-form input,.uk-form select,.uk-form textarea {
  -moz-box-sizing: border-box;
  box-sizing: border-box;
  margin: 0;
  border-radius: 0;
  font: inherit;
  color: inherit;
}
```
