### ISSUE TITLE
SCSS problem with .uk-grid

### ISSUE THREAD

**Issue by borodiychuk** [uikit/uikit#707]
The SCSS code 

``` scss
$grid-gutter-horizontal: 25px !default;
...
.uk-grid {
    /* 1 */
    margin: 0 0 0 -$grid-gutter-horizontal;
    /* 2 */
    padding: 0;
    list-style: none;
}
```

gets compiled into

``` css
.uk-grid {
  /* 1 */
  margin: 0 0 -25px;
  /* 2 */
  padding: 0;
  list-style: none;
}
```

where instead of `margin 0 0 0 -25px;` we have  `margin 0 0 -25px;` and left margin becomes 0.

To solve this the SCSS line 79 in bower-uikit/scss/core/grid.scss

``` scss
    margin: 0 0 0 -$grid-gutter-horizontal;
```

has to be replaced with

``` scss
    margin: 0 0 0 0-$grid-gutter-horizontal;
```
