### ISSUE TITLE
2.13.1+ radio styling issue in distributive (not customizer)

### ISSUE THREAD

**Issue by nazar-pc** [uikit/uikit#788]
In distributive on GitHub (almost flat theme) there is no such styling for radio/checkbox:
```css
.uk-form input[type="radio"],
.uk-form input[type="checkbox"] {
  display: inline-block;
  height: 14px;
  width: 14px;
  border: 1px solid #aaaaaa;
  overflow: hidden;
  margin-top: -4px;
  vertical-align: middle;
  -webkit-appearance: none;
  outline: 0;
  background: transparent;
}
```
However, if build the same theme in customizer - everything works fine.
Didn't try 2.13.0, but 2.13.1 and 2.14.0 affected, 2.12.0 works fine.
