### ISSUE TITLE
Feature request: fixed-width icon

### ISSUE THREAD

**Issue by jerry1970** [uikit/uikit#885]
The Font-Awesome css contains fa-fw for fixed-width icons, which looks better when using a list with every line starting with different icons. I could not find something similar in ui-kit.

I now added this in a uikit-override.css, which works OK, but not very well when I use larger icons. I didn't need that so I stopped looking for a better solution, but it would be nice to have this in the default CSS set.
``` css
.uk-icon-fw {
	text-align: center;
	width: 1.28571em;
}
```
