### ISSUE TITLE
[Proposal] Form select with multiple attribute ( such as Tags Autocomplete )

### ISSUE THREAD

**Issue by Landish** [uikit/uikit#944]
First of all, I want to thank you for a such a great framework. 

It's clean, it's simple, it has all necessary styling and components and I really like it.

Only thing what I'm missing is ability to use form select element with multiple attribute, such as tags. 

Something like this: 
http://xoxco.com/projects/code/tagsinput/

It would be nice to have a functionality like this, it would make it more perfect than it is now.

**Comment by jerry1970** [comment]
I use select2 for that:
http://select2.github.io/
I use that to style even simple select dropdowns so they all look the same. The select2 CSS needs some tweaking to make it look like the rest of UIKit, though.

**Comment by Landish** [comment]
Thanks @jerry1970, but I'm familiar with Select2 plugin.

But, all I want to do, is to use this framework without any 3rd-party integration.

**Comment by jerry1970** [comment]
Fair enough. But I think select2 has so much in it that it will take a while before this is copied into UIKit. Plus, I would understand if no one would touch this because select2 is good enough already.

Although I like almost all of UIKit, the form elements for checkbox, radio, and select could use some improvement. Checbox and radio are in the Form Advanced add-on, but I prefer a CSS only solution that simply hides the original control and shows something else in place. That way you have the same focus and navigation abilities as with regular inputs (well, they are regular inputs, you just don't see them).

**Comment by saschadube** [comment]
Thanks, we will keep it in mind for future development.

**Comment by kevinresol** [comment]
@jerry1970 how do you customize the css of the select2 elements?

**Comment by jerry1970** [comment]
@kevinresol, that was not very easy. Select2 has a lot of CSS elements to style. To be honest, the logic and structure of their CSS classes looks like it could be a lot simpler.

I currently have the following but this is in an unfinished project from a few months ago so I don't remember whether it needs more:

```css
.select2-container .select2-choice {
	background-image: none;
	transition: all 0.2s linear 0s;
	border-color: #ddd;
}
.select2-container .select2-choice .select2-arrow {
	background: none;
	border-left: none;
}

.select2-container-active .select2-choice, .select2-container-active .select2-choices {
	box-shadow: none;
	background: none repeat scroll 0 0 #f5fbfe;
	border-color: #99baca;
}
.select2-drop {
	box-shadow: none;
	border-color: #99baca;
}
```
