### ISSUE TITLE
Button mini with icon

### ISSUE THREAD

**Issue by adaniello** [uikit/uikit#976]
Hi,
if you try to use a button mini with an icon, the icon seem not centered vertically, but slightly shifted to the top.

```html
<button type="button" class="uk-button uk-button-mini">
<i class="uk-icon-plus"></i>
</button>
```

I solve with this css:
```css
.uk-button-mini > [class*=uk-icon-] { font-size: 10px; line-height: 20px; } 
```
but think that must be fixed in UiKit.

Same issue with other button size modifiers.

Thanks
